-- Chạy file này trên db-food-deli
INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (201, 201, 'Góc ẩm thực Gà Rán Hương Thảo', 'restaurant1@gmail.com', '0988888881', 'Số 191 Nguyễn Trãi, Ba Đình, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (201, 'Gà chiên giòn cay - Công thức gia truyền', 'Gà chiên giòn cay - Công thức gia truyền ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (201, 'Combo gà gia đình - Đặc sản', 'Combo gà gia đình - Đặc sản ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (201, 'Gà sốt BBQ Hàn Quốc - Đậm vị', 'Gà sốt BBQ Hàn Quốc - Đậm vị ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (201, 'Cánh gà phô mai - Công thức gia truyền', 'Cánh gà phô mai - Công thức gia truyền ngon tuyệt hảo', 60000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (202, 202, 'Hẻm Hải Sản Hà Thành', 'restaurant2@gmail.com', '0988888882', 'Số 101 Tôn Đức Thắng, Hoàn Kiếm, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (202, 'Bạch tuộc xào cay - Giòn rụm', 'Bạch tuộc xào cay - Giòn rụm ngon tuyệt hảo', 50000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (202, 'Cua rang me - Công thức gia truyền', 'Cua rang me - Công thức gia truyền ngon tuyệt hảo', 50000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (202, 'Hàu nướng phô mai - Giòn rụm', 'Hàu nướng phô mai - Giòn rụm ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (202, 'Tôm sú háp gừng - Siêu to khổng lồ', 'Tôm sú háp gừng - Siêu to khổng lồ ngon tuyệt hảo', 40000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (203, 203, 'Quán Phở Bà Út', 'restaurant3@gmail.com', '0988888883', 'Số 5 Thái Hà, Đống Đa, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (203, 'Phở xào bò mềm - Hương vị mới', 'Phở xào bò mềm - Hương vị mới ngon tuyệt hảo', 70000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (203, 'Phở bò tái nạm - Công thức gia truyền', 'Phở bò tái nạm - Công thức gia truyền ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (203, 'Phở bò gầu gân - Giòn rụm', 'Phở bò gầu gân - Giòn rụm ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (203, 'Phở gà ta xé phay - Công thức gia truyền', 'Phở gà ta xé phay - Công thức gia truyền ngon tuyệt hảo', 70000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (204, 204, 'Góc ẩm thực Sushi 36 Phố Phường', 'restaurant4@gmail.com', '0988888884', 'Số 153 Nguyễn Trãi, Ba Đình, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (204, 'Sushi cá hồi - Size L', 'Sushi cá hồi - Size L ngon tuyệt hảo', 70000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (204, 'Sashimi tổng hợp - Công thức gia truyền', 'Sashimi tổng hợp - Công thức gia truyền ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (204, 'Cơm cuộn tôm chiên - Size L', 'Cơm cuộn tôm chiên - Size L ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (204, 'Sushi trứng cá hồi - Size L', 'Sushi trứng cá hồi - Size L ngon tuyệt hảo', 50000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (205, 205, 'Bếp Phở Mộc', 'restaurant5@gmail.com', '0988888885', 'Số 224 Giảng Võ, Tây Hồ, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (205, 'Phở gà ta xé phay - Giòn rụm', 'Phở gà ta xé phay - Giòn rụm ngon tuyệt hảo', 50000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (205, 'Phở bò gầu gân - Siêu to khổng lồ', 'Phở bò gầu gân - Siêu to khổng lồ ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (205, 'Phở xào bò mềm - Hương vị mới', 'Phở xào bò mềm - Hương vị mới ngon tuyệt hảo', 50000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (205, 'Phở đặc biệt bát đá - Công thức gia truyền', 'Phở đặc biệt bát đá - Công thức gia truyền ngon tuyệt hảo', 50000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (206, 206, 'Nhà hàng Cơm Tấm Gia Truyền', 'restaurant6@gmail.com', '0988888886', 'Số 34 Nguyễn Trãi, Đống Đa, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (206, 'Cơm tấm sườn bì chả - Đặc sản', 'Cơm tấm sườn bì chả - Đặc sản ngon tuyệt hảo', 70000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (206, 'Cơm tấm chả cua - Đặc sản', 'Cơm tấm chả cua - Đặc sản ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (206, 'Cơm tấm cốt lết - Công thức gia truyền', 'Cơm tấm cốt lết - Công thức gia truyền ngon tuyệt hảo', 70000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (206, 'Cơm tấm đùi gà nướng - Siêu to khổng lồ', 'Cơm tấm đùi gà nướng - Siêu to khổng lồ ngon tuyệt hảo', 50000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (207, 207, 'Hương vị Sushi Gia Truyền', 'restaurant7@gmail.com', '0988888887', 'Số 130 Kim Mã, Hoàng Mai, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (207, 'Sushi cá hồi - Đậm vị', 'Sushi cá hồi - Đậm vị ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (207, 'Maki bào ngư - Đặc sản', 'Maki bào ngư - Đặc sản ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (207, 'Sashimi tổng hợp - Siêu to khổng lồ', 'Sashimi tổng hợp - Siêu to khổng lồ ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (207, 'Sushi trứng cá hồi - Size L', 'Sushi trứng cá hồi - Size L ngon tuyệt hảo', 80000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (208, 208, 'Hẻm Gà Rán Xưa', 'restaurant8@gmail.com', '0988888888', 'Số 90 Thái Hà, Long Biên, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (208, 'Gà chiên giòn cay - Công thức gia truyền', 'Gà chiên giòn cay - Công thức gia truyền ngon tuyệt hảo', 50000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (208, 'Combo gà gia đình - Đặc sản', 'Combo gà gia đình - Đặc sản ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (208, 'Cánh gà phô mai - Giòn rụm', 'Cánh gà phô mai - Giòn rụm ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (208, 'Gà xào tuyết yến - Size L', 'Gà xào tuyết yến - Size L ngon tuyệt hảo', 40000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (209, 209, 'Nhà hàng Chay Bà Út', 'restaurant9@gmail.com', '0988888889', 'Số 3 Xã Đàn, Long Biên, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (209, 'Miến xào nấm đông cô - Siêu to khổng lồ', 'Miến xào nấm đông cô - Siêu to khổng lồ ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (209, 'Lẩu nấm chay - Siêu to khổng lồ', 'Lẩu nấm chay - Siêu to khổng lồ ngon tuyệt hảo', 70000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (209, 'Gỏi cuốn nấm - Đặc sản', 'Gỏi cuốn nấm - Đặc sản ngon tuyệt hảo', 50000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (209, 'Bún chay chua cay - Siêu to khổng lồ', 'Bún chay chua cay - Siêu to khổng lồ ngon tuyệt hảo', 80000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (210, 210, 'Tiệm ăn Phở Bà Út', 'restaurant10@gmail.com', '0988888810', 'Số 211 Đội Cấn, Long Biên, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (210, 'Phở bò tái nạm - Siêu to khổng lồ', 'Phở bò tái nạm - Siêu to khổng lồ ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (210, 'Phở xào bò mềm - Công thức gia truyền', 'Phở xào bò mềm - Công thức gia truyền ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (210, 'Phở bò gầu gân - Hương vị mới', 'Phở bò gầu gân - Hương vị mới ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (210, 'Phở gà ta xé phay - Hương vị mới', 'Phở gà ta xé phay - Hương vị mới ngon tuyệt hảo', 60000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (211, 211, 'Góc ẩm thực Hải Sản Xưa', 'restaurant11@gmail.com', '0988888811', 'Số 134 Tôn Đức Thắng, Đống Đa, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (211, 'Tôm sú háp gừng - Giòn rụm', 'Tôm sú háp gừng - Giòn rụm ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (211, 'Mực nướng mỡ hành - Đậm vị', 'Mực nướng mỡ hành - Đậm vị ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (211, 'Bạch tuộc xào cay - Size L', 'Bạch tuộc xào cay - Size L ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (211, 'Hàu nướng phô mai - Đậm vị', 'Hàu nướng phô mai - Đậm vị ngon tuyệt hảo', 80000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (212, 212, 'Bếp Bún Bò Gia Truyền', 'restaurant12@gmail.com', '0988888812', 'Số 193 Hoàng Hoa Thám, Hai Bà Trưng, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (212, 'Bún bò giò heo - Siêu to khổng lồ', 'Bún bò giò heo - Siêu to khổng lồ ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (212, 'Bún bò nạm chả - Công thức gia truyền', 'Bún bò nạm chả - Công thức gia truyền ngon tuyệt hảo', 50000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (212, 'Bún bò bắp hoa - Công thức gia truyền', 'Bún bò bắp hoa - Công thức gia truyền ngon tuyệt hảo', 70000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (212, 'Bún bò gân - Đậm vị', 'Bún bò gân - Đậm vị ngon tuyệt hảo', 80000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (213, 213, 'Quán Bún Bò Hương Thảo', 'restaurant13@gmail.com', '0988888813', 'Số 61 Kim Mã, Đống Đa, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (213, 'Bún bò bắp hoa - Hương vị mới', 'Bún bò bắp hoa - Hương vị mới ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (213, 'Bún bò giò heo - Siêu to khổng lồ', 'Bún bò giò heo - Siêu to khổng lồ ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (213, 'Bún bò nạm chả - Đậm vị', 'Bún bò nạm chả - Đậm vị ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (213, 'Bún bò gân - Hương vị mới', 'Bún bò gân - Hương vị mới ngon tuyệt hảo', 40000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (214, 214, 'Hẻm Pizza Than Hoa', 'restaurant14@gmail.com', '0988888814', 'Số 136 Kim Mã, Long Biên, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (214, 'Pizza thượng hạng - Đặc sản', 'Pizza thượng hạng - Đặc sản ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (214, 'Pizza xúc xích pepperoni - Đậm vị', 'Pizza xúc xích pepperoni - Đậm vị ngon tuyệt hảo', 70000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (214, 'Pizza bò dứa - Hương vị mới', 'Pizza bò dứa - Hương vị mới ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (214, 'Pizza phô mai nấm - Đặc sản', 'Pizza phô mai nấm - Đặc sản ngon tuyệt hảo', 60000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (215, 215, 'Bếp Phở Than Hoa', 'restaurant15@gmail.com', '0988888815', 'Số 80 Trần Duy Hưng, Thanh Xuân, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (215, 'Phở xào bò mềm - Giòn rụm', 'Phở xào bò mềm - Giòn rụm ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (215, 'Phở bò tái nạm - Siêu to khổng lồ', 'Phở bò tái nạm - Siêu to khổng lồ ngon tuyệt hảo', 50000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (215, 'Phở bò gầu gân - Công thức gia truyền', 'Phở bò gầu gân - Công thức gia truyền ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (215, 'Phở gà ta xé phay - Công thức gia truyền', 'Phở gà ta xé phay - Công thức gia truyền ngon tuyệt hảo', 80000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (216, 216, 'Hương vị Hải Sản Gia Truyền', 'restaurant16@gmail.com', '0988888816', 'Số 235 Thái Hà, Hoàng Mai, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (216, 'Cua rang me - Giòn rụm', 'Cua rang me - Giòn rụm ngon tuyệt hảo', 50000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (216, 'Hàu nướng phô mai - Hương vị mới', 'Hàu nướng phô mai - Hương vị mới ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (216, 'Mực nướng mỡ hành - Công thức gia truyền', 'Mực nướng mỡ hành - Công thức gia truyền ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (216, 'Tôm sú háp gừng - Giòn rụm', 'Tôm sú háp gừng - Giòn rụm ngon tuyệt hảo', 40000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (217, 217, 'Bếp Sushi Sài Gòn', 'restaurant17@gmail.com', '0988888817', 'Số 194 Hoàng Hoa Thám, Nam Từ Liêm, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (217, 'Cơm cuộn tôm chiên - Siêu to khổng lồ', 'Cơm cuộn tôm chiên - Siêu to khổng lồ ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (217, 'Maki bào ngư - Đậm vị', 'Maki bào ngư - Đậm vị ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (217, 'Sashimi tổng hợp - Công thức gia truyền', 'Sashimi tổng hợp - Công thức gia truyền ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (217, 'Sushi trứng cá hồi - Công thức gia truyền', 'Sushi trứng cá hồi - Công thức gia truyền ngon tuyệt hảo', 70000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (218, 218, 'Nhà hàng Trà Sữa Bà Út', 'restaurant18@gmail.com', '0988888818', 'Số 9 Phố Huế, Hoàng Mai, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (218, 'Lục trà macchiato - Giòn rụm', 'Lục trà macchiato - Giòn rụm ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (218, 'Trà mãng cầu - Giòn rụm', 'Trà mãng cầu - Giòn rụm ngon tuyệt hảo', 70000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (218, 'Oolong vải thiều - Công thức gia truyền', 'Oolong vải thiều - Công thức gia truyền ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (218, 'Trà sữa trân châu đường đen - Đậm vị', 'Trà sữa trân châu đường đen - Đậm vị ngon tuyệt hảo', 70000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (219, 219, 'Tiệm ăn Hải Sản Ba Cây Chổi', 'restaurant19@gmail.com', '0988888819', 'Số 249 Hoàng Hoa Thám, Hai Bà Trưng, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (219, 'Hàu nướng phô mai - Giòn rụm', 'Hàu nướng phô mai - Giòn rụm ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (219, 'Cua rang me - Size L', 'Cua rang me - Size L ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (219, 'Bạch tuộc xào cay - Size L', 'Bạch tuộc xào cay - Size L ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (219, 'Tôm sú háp gừng - Đậm vị', 'Tôm sú háp gừng - Đậm vị ngon tuyệt hảo', 60000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (220, 220, 'Tiệm ăn Phở Đồng Quê', 'restaurant20@gmail.com', '0988888820', 'Số 18 Phố Huế, Thanh Xuân, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (220, 'Phở xào bò mềm - Giòn rụm', 'Phở xào bò mềm - Giòn rụm ngon tuyệt hảo', 70000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (220, 'Phở gà ta xé phay - Size L', 'Phở gà ta xé phay - Size L ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (220, 'Phở bò gầu gân - Siêu to khổng lồ', 'Phở bò gầu gân - Siêu to khổng lồ ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (220, 'Phở đặc biệt bát đá - Hương vị mới', 'Phở đặc biệt bát đá - Hương vị mới ngon tuyệt hảo', 80000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (221, 221, 'Tiệm ăn Chay Xưa', 'restaurant21@gmail.com', '0988888821', 'Số 157 Kim Mã, Hai Bà Trưng, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (221, 'Cơm lá sen chay - Đặc sản', 'Cơm lá sen chay - Đặc sản ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (221, 'Bún chay chua cay - Hương vị mới', 'Bún chay chua cay - Hương vị mới ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (221, 'Gỏi cuốn nấm - Đậm vị', 'Gỏi cuốn nấm - Đậm vị ngon tuyệt hảo', 50000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (221, 'Miến xào nấm đông cô - Giòn rụm', 'Miến xào nấm đông cô - Giòn rụm ngon tuyệt hảo', 60000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (222, 222, 'Hẻm Phở Đồng Quê', 'restaurant22@gmail.com', '0988888822', 'Số 158 Trần Duy Hưng, Hoàn Kiếm, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (222, 'Phở đặc biệt bát đá - Size L', 'Phở đặc biệt bát đá - Size L ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (222, 'Phở xào bò mềm - Công thức gia truyền', 'Phở xào bò mềm - Công thức gia truyền ngon tuyệt hảo', 70000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (222, 'Phở gà ta xé phay - Giòn rụm', 'Phở gà ta xé phay - Giòn rụm ngon tuyệt hảo', 70000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (222, 'Phở bò gầu gân - Giòn rụm', 'Phở bò gầu gân - Giòn rụm ngon tuyệt hảo', 80000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (223, 223, 'Hẻm Cơm Tấm Cô Tấm', 'restaurant23@gmail.com', '0988888823', 'Số 100 Phố Huế, Ba Đình, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (223, 'Cơm tấm sườn bì chả - Giòn rụm', 'Cơm tấm sườn bì chả - Giòn rụm ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (223, 'Cơm tấm chả cua - Size L', 'Cơm tấm chả cua - Size L ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (223, 'Cơm tấm cốt lết - Hương vị mới', 'Cơm tấm cốt lết - Hương vị mới ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (223, 'Cơm tấm sườn mỡ hành - Size L', 'Cơm tấm sườn mỡ hành - Size L ngon tuyệt hảo', 70000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (224, 224, 'Tiệm ăn Cơm Tấm Nhà Làm', 'restaurant24@gmail.com', '0988888824', 'Số 238 Nguyễn Trãi, Ba Đình, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (224, 'Cơm tấm sườn bì chả - Công thức gia truyền', 'Cơm tấm sườn bì chả - Công thức gia truyền ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (224, 'Cơm tấm sườn mỡ hành - Hương vị mới', 'Cơm tấm sườn mỡ hành - Hương vị mới ngon tuyệt hảo', 70000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (224, 'Cơm tấm chả cua - Size L', 'Cơm tấm chả cua - Size L ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (224, 'Cơm tấm cốt lết - Size L', 'Cơm tấm cốt lết - Size L ngon tuyệt hảo', 70000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (225, 225, 'Tiệm ăn Sushi Hà Thành', 'restaurant25@gmail.com', '0988888825', 'Số 44 Thái Hà, Nam Từ Liêm, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (225, 'Sushi cá hồi - Siêu to khổng lồ', 'Sushi cá hồi - Siêu to khổng lồ ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (225, 'Sashimi tổng hợp - Hương vị mới', 'Sashimi tổng hợp - Hương vị mới ngon tuyệt hảo', 50000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (225, 'Maki bào ngư - Đặc sản', 'Maki bào ngư - Đặc sản ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (225, 'Cơm cuộn tôm chiên - Giòn rụm', 'Cơm cuộn tôm chiên - Giòn rụm ngon tuyệt hảo', 40000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (226, 226, 'Tiệm ăn Lẩu Cua Đồng Hương Thảo', 'restaurant26@gmail.com', '0988888826', 'Số 235 Thái Hà, Ba Đình, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (226, 'Lẩu cua đồng sườn sụn - Hương vị mới', 'Lẩu cua đồng sườn sụn - Hương vị mới ngon tuyệt hảo', 70000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (226, 'Lẩu ếch măng cay - Giòn rụm', 'Lẩu ếch măng cay - Giòn rụm ngon tuyệt hảo', 50000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (226, 'Lẩu riêu bắp bò - Size L', 'Lẩu riêu bắp bò - Size L ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (226, 'Lẩu riêu cua ốc - Hương vị mới', 'Lẩu riêu cua ốc - Hương vị mới ngon tuyệt hảo', 60000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (227, 227, 'Góc ẩm thực Chay Chợ Lớn', 'restaurant27@gmail.com', '0988888827', 'Số 185 Tôn Đức Thắng, Long Biên, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (227, 'Miến xào nấm đông cô - Giòn rụm', 'Miến xào nấm đông cô - Giòn rụm ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (227, 'Cơm lá sen chay - Đậm vị', 'Cơm lá sen chay - Đậm vị ngon tuyệt hảo', 60000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (227, 'Lẩu nấm chay - Giòn rụm', 'Lẩu nấm chay - Giòn rụm ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (227, 'Bún chay chua cay - Hương vị mới', 'Bún chay chua cay - Hương vị mới ngon tuyệt hảo', 70000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (228, 228, 'Bếp Gà Rán Chợ Lớn', 'restaurant28@gmail.com', '0988888828', 'Số 226 Thái Hà, Tây Hồ, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (228, 'Cánh gà phô mai - Giòn rụm', 'Cánh gà phô mai - Giòn rụm ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (228, 'Gà chiên giòn cay - Đậm vị', 'Gà chiên giòn cay - Đậm vị ngon tuyệt hảo', 70000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (228, 'Gà xào tuyết yến - Hương vị mới', 'Gà xào tuyết yến - Hương vị mới ngon tuyệt hảo', 50000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (228, 'Combo gà gia đình - Đặc sản', 'Combo gà gia đình - Đặc sản ngon tuyệt hảo', 40000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (229, 229, 'Góc ẩm thực Chay Chợ Lớn', 'restaurant29@gmail.com', '0988888829', 'Số 18 Nguyễn Trãi, Cầu Giấy, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (229, 'Miến xào nấm đông cô - Đặc sản', 'Miến xào nấm đông cô - Đặc sản ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (229, 'Lẩu nấm chay - Hương vị mới', 'Lẩu nấm chay - Hương vị mới ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (229, 'Gỏi cuốn nấm - Siêu to khổng lồ', 'Gỏi cuốn nấm - Siêu to khổng lồ ngon tuyệt hảo', 40000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (229, 'Bún chay chua cay - Đặc sản', 'Bún chay chua cay - Đặc sản ngon tuyệt hảo', 60000, 1, true);

INSERT INTO public.restaurants (id, owner_id, name, email, phone, address, description, status, verification_status) VALUES (230, 230, 'Hương vị Chay Hương Thảo', 'restaurant30@gmail.com', '0988888830', 'Số 194 Tôn Đức Thắng, Nam Từ Liêm, Hà Nội', 'Một quán ăn tuyệt vời với hương vị vô cùng đặc trưng.', 'active', 'approved') ON CONFLICT DO NOTHING;
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (230, 'Gỏi cuốn nấm - Đậm vị', 'Gỏi cuốn nấm - Đậm vị ngon tuyệt hảo', 80000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (230, 'Lẩu nấm chay - Size L', 'Lẩu nấm chay - Size L ngon tuyệt hảo', 50000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (230, 'Miến xào nấm đông cô - Siêu to khổng lồ', 'Miến xào nấm đông cô - Siêu to khổng lồ ngon tuyệt hảo', 70000, 1, true);
INSERT INTO public.foods (restaurant_id, food_name, description, price, primary_category_id, is_available) VALUES (230, 'Bún chay chua cay - Size L', 'Bún chay chua cay - Size L ngon tuyệt hảo', 60000, 1, true);


SELECT setval('public.restaurants_restaurant_id_seq', (SELECT MAX(id) FROM public.restaurants));
